# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='IncomingPushMessageSignal.proto',
  package='textsecure',
  serialized_pb=b'\n\x1fIncomingPushMessageSignal.proto\x12\ntextsecure\"\x87\x02\n\x19IncomingPushMessageSignal\x12\x38\n\x04type\x18\x01 \x01(\x0e\x32*.textsecure.IncomingPushMessageSignal.Type\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x14\n\x0csourceDevice\x18\x07 \x01(\r\x12\r\n\x05relay\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12\x0f\n\x07message\x18\x06 \x01(\x0c\"W\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nCIPHERTEXT\x10\x01\x12\x10\n\x0cKEY_EXCHANGE\x10\x02\x12\x11\n\rPREKEY_BUNDLE\x10\x03\x12\r\n\tPLAINTEXT\x10\x04\"\x87\x04\n\x12PushMessageContent\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\x12\x45\n\x0b\x61ttachments\x18\x02 \x03(\x0b\x32\x30.textsecure.PushMessageContent.AttachmentPointer\x12:\n\x05group\x18\x03 \x01(\x0b\x32+.textsecure.PushMessageContent.GroupContext\x12\r\n\x05\x66lags\x18\x04 \x01(\r\x1a\x41\n\x11\x41ttachmentPointer\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x13\n\x0b\x63ontentType\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\x0c\x1a\xf3\x01\n\x0cGroupContext\x12\n\n\x02id\x18\x01 \x01(\x0c\x12>\n\x04type\x18\x02 \x01(\x0e\x32\x30.textsecure.PushMessageContent.GroupContext.Type\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07members\x18\x04 \x03(\t\x12@\n\x06\x61vatar\x18\x05 \x01(\x0b\x32\x30.textsecure.PushMessageContent.AttachmentPointer\"6\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\x0b\n\x07\x44\x45LIVER\x10\x02\x12\x08\n\x04QUIT\x10\x03\"\x18\n\x05\x46lags\x12\x0f\n\x0b\x45ND_SESSION\x10\x01\x42\x37\n\"org.whispersystems.textsecure.pushB\x11PushMessageProtos')



_INCOMINGPUSHMESSAGESIGNAL_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='textsecure.IncomingPushMessageSignal.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CIPHERTEXT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='KEY_EXCHANGE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PREKEY_BUNDLE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PLAINTEXT', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=224,
  serialized_end=311,
)

_PUSHMESSAGECONTENT_GROUPCONTEXT_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='textsecure.PushMessageContent.GroupContext.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UPDATE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DELIVER', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='QUIT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=753,
  serialized_end=807,
)

_PUSHMESSAGECONTENT_FLAGS = descriptor.EnumDescriptor(
  name='Flags',
  full_name='textsecure.PushMessageContent.Flags',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='END_SESSION', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=809,
  serialized_end=833,
)


_INCOMINGPUSHMESSAGESIGNAL = descriptor.Descriptor(
  name='IncomingPushMessageSignal',
  full_name='textsecure.IncomingPushMessageSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='textsecure.IncomingPushMessageSignal.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source', full_name='textsecure.IncomingPushMessageSignal.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode("utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sourceDevice', full_name='textsecure.IncomingPushMessageSignal.sourceDevice', index=2,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='relay', full_name='textsecure.IncomingPushMessageSignal.relay', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode("utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='textsecure.IncomingPushMessageSignal.timestamp', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='textsecure.IncomingPushMessageSignal.message', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INCOMINGPUSHMESSAGESIGNAL_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=311,
)


_PUSHMESSAGECONTENT_ATTACHMENTPOINTER = descriptor.Descriptor(
  name='AttachmentPointer',
  full_name='textsecure.PushMessageContent.AttachmentPointer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='textsecure.PushMessageContent.AttachmentPointer.id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contentType', full_name='textsecure.PushMessageContent.AttachmentPointer.contentType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode("utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key', full_name='textsecure.PushMessageContent.AttachmentPointer.key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=496,
  serialized_end=561,
)

_PUSHMESSAGECONTENT_GROUPCONTEXT = descriptor.Descriptor(
  name='GroupContext',
  full_name='textsecure.PushMessageContent.GroupContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='textsecure.PushMessageContent.GroupContext.id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='textsecure.PushMessageContent.GroupContext.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='textsecure.PushMessageContent.GroupContext.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode("utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='members', full_name='textsecure.PushMessageContent.GroupContext.members', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='avatar', full_name='textsecure.PushMessageContent.GroupContext.avatar', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PUSHMESSAGECONTENT_GROUPCONTEXT_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=564,
  serialized_end=807,
)

_PUSHMESSAGECONTENT = descriptor.Descriptor(
  name='PushMessageContent',
  full_name='textsecure.PushMessageContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='body', full_name='textsecure.PushMessageContent.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode("utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attachments', full_name='textsecure.PushMessageContent.attachments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='group', full_name='textsecure.PushMessageContent.group', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='textsecure.PushMessageContent.flags', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PUSHMESSAGECONTENT_ATTACHMENTPOINTER, _PUSHMESSAGECONTENT_GROUPCONTEXT, ],
  enum_types=[
    _PUSHMESSAGECONTENT_FLAGS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=314,
  serialized_end=833,
)

_INCOMINGPUSHMESSAGESIGNAL.fields_by_name['type'].enum_type = _INCOMINGPUSHMESSAGESIGNAL_TYPE
_INCOMINGPUSHMESSAGESIGNAL_TYPE.containing_type = _INCOMINGPUSHMESSAGESIGNAL;
_PUSHMESSAGECONTENT_ATTACHMENTPOINTER.containing_type = _PUSHMESSAGECONTENT;
_PUSHMESSAGECONTENT_GROUPCONTEXT.fields_by_name['type'].enum_type = _PUSHMESSAGECONTENT_GROUPCONTEXT_TYPE
_PUSHMESSAGECONTENT_GROUPCONTEXT.fields_by_name['avatar'].message_type = _PUSHMESSAGECONTENT_ATTACHMENTPOINTER
_PUSHMESSAGECONTENT_GROUPCONTEXT.containing_type = _PUSHMESSAGECONTENT;
_PUSHMESSAGECONTENT_GROUPCONTEXT_TYPE.containing_type = _PUSHMESSAGECONTENT_GROUPCONTEXT;
_PUSHMESSAGECONTENT.fields_by_name['attachments'].message_type = _PUSHMESSAGECONTENT_ATTACHMENTPOINTER
_PUSHMESSAGECONTENT.fields_by_name['group'].message_type = _PUSHMESSAGECONTENT_GROUPCONTEXT
_PUSHMESSAGECONTENT_FLAGS.containing_type = _PUSHMESSAGECONTENT;
DESCRIPTOR.message_types_by_name['IncomingPushMessageSignal'] = _INCOMINGPUSHMESSAGESIGNAL
DESCRIPTOR.message_types_by_name['PushMessageContent'] = _PUSHMESSAGECONTENT

IncomingPushMessageSignal = reflection.GeneratedProtocolMessageType('IncomingPushMessageSignal', (message.Message,),
    {
      'DESCRIPTOR': _INCOMINGPUSHMESSAGESIGNAL,
      # @@protoc_insertion_point(class_scope:textsecure.IncomingPushMessageSignal)
    })

PushMessageContent = reflection.GeneratedProtocolMessageType('PushMessageContent', (message.Message,),
    {
      'DESCRIPTOR': _PUSHMESSAGECONTENT,
      'AttachmentPointer': reflection.GeneratedProtocolMessageType('AttachmentPointer', (message.Message,),
          {
            'DESCRIPTOR': _PUSHMESSAGECONTENT_ATTACHMENTPOINTER,
            # @@protoc_insertion_point(class_scope:textsecure.PushMessageContent.AttachmentPointer)
          }),
      'GroupContext': reflection.GeneratedProtocolMessageType('GroupContext', (message.Message,),
          {
            'DESCRIPTOR': _PUSHMESSAGECONTENT_GROUPCONTEXT,
            # @@protoc_insertion_point(class_scope:textsecure.PushMessageContent.GroupContext)
          }),
      # @@protoc_insertion_point(class_scope:textsecure.PushMessageContent)
    })

# @@protoc_insertion_point(module_scope)
